name: Deploy Docker Compose to GCP

on:
  push:
    branches:
      - main  # Hoặc branch bạn muốn deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy docker-compose.yml to server
      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SSH_USER }}/"

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.7.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}
            docker-compose pull
            docker-compose up -d --remove-orphans
